### ISSUE TITLE
Threads cannot be found

### ISSUE THREAD

**Issue by gvanbrakel** [ibissource/ibis-ladybug#50]
When running iaf-test, the log file testtool4ibis4test.log fills with messages 'Unknown thread, ignored checkpoint'.
To reproduce:
1) start iaf-test
2) run larva scenario 'ApiListener Simple Insert
3) view log file testtool4ibis4test.log

**Comment by jacodg** [comment]
This is caused by an HttpSender calling and ApiListener within the same Ibis. The ApiListener will run in a different thread (e.g. http-nio-80-exec-5 instead of Thread-6) but the correlationId is passed on between the two adapters. As threadCreatepoint() and threadStartpoint() are not used the thread is unknow for the report in progress for this correlationId. With https://github.com/ibissource/ibis-ladybug/commit/28d5db5ace2be008469fd4fac670b4d129f06079 and https://github.com/ibissource/iaf/pull/1376 the threads are now added to the report but with a warning.

Together with https://github.com/ibissource/iaf/pull/1351 most warnings are gone when running all Ibis4Test test scenario's.
